name: cicd

on:
  push:
    branches:
      - main

jobs:
  lint-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: stoplightio/spectral-action@latest
        with:
          file_glob: '*.json'
      
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiridj/wm-apigw-actions-register-api@v1
        with: 
          apigw-url: ${{ secrets.APIGW_URL }}
          apigw-username: ${{ secrets.APIGW_USERNAME }}
          apigw-password: ${{ secrets.APIGW_PASSWORD }}
          api-spec: swagger.json
          set-active: true
          debug: ${{ secrets.ACTIONS_STEP_DEBUG }}
